// Generated by CoffeeScript 1.10.0
(function() {
  var CND, MKNCR, O, alert, badge, debug, echo, help, info, log, rpr, urge, warn, whisper,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MOJIKURA-IDL/IDL';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  MKNCR = require('mingkwai-ncr');

  O = require('./options');

  this._parser_settings = O.idl;

  this._new_parse = function(source) {
    var R;
    R = {
      '~isa': 'MOJIKURA-IDL/parse',
      source: source,
      idx: 0,
      grammar: this._parser_settings
    };
    R.tokens = this._tokenize(R, source);
    return R;
  };

  this.tokenize = function(source) {
    return (this._new_parse(source)).tokens;
  };

  this._tokenize = function(me, source) {
    var R, chrs, i, idx, len, symbol;
    R = [];
    chrs = MKNCR.chrs_from_text(source);
    for (idx = i = 0, len = chrs.length; i < len; idx = ++i) {
      symbol = chrs[idx];
      R.push(this._new_token(me, symbol, idx));
    }
    return R;
  };

  this._new_token = function(me, symbol, idx) {
    var R, operator, type;
    type = this._type_of_symbol(me, symbol);
    symbol = MKNCR.jzr_as_uchr(symbol);

    /* `t` for 'type' */
    R = {
      '~isa': 'MOJIKURA-IDL/token',
      s: symbol,
      idx: idx,
      t: type
    };
    switch (type) {
      case 'operator':
        operator = this._operator_from_symbol(me, symbol);
        R.a = operator.arity;
        R.n = operator.name;
    }
    return R;
  };

  this._isa_token = function(me, x) {
    return CND.isa(x, 'MOJIKURA-IDL/token');
  };

  this._rpr_tokens = function(me, error_idx) {
    var R, i, idx, len, ref, token;
    if (error_idx == null) {
      error_idx = null;
    }
    if (error_idx == null) {
      error_idx = me.idx;
    }
    R = [];
    ref = me.tokens;
    for (idx = i = 0, len = ref.length; i < len; idx = ++i) {
      token = ref[idx];
      R.push(idx === error_idx ? CND.red(" ✘ " + token.s + " ✘ ") : CND.white("" + token.s));
    }
    return CND.white("[ " + (R.join('')) + " ]");
  };

  this._operator_from_symbol = function(me, symbol) {
    var R;
    if ((R = me.grammar.operators[symbol]) == null) {
      throw new Error("unknown operator " + (rpr(symbol)));
    }
    return R;
  };

  this._describe_symbol = function(me, symbol) {
    return MKNCR.describe(symbol);
  };

  this._tags_from_symbol = function(me, symbol) {
    var ref;
    return (ref = (this._describe_symbol(me, symbol)).tag) != null ? ref : [];
  };

  this._symbol_is_operator = function(me, symbol) {
    return symbol in me.grammar.operators;
  };

  this._symbol_is_component = function(me, symbol) {
    return indexOf.call(this._tags_from_symbol(me, symbol), 'cjk') >= 0;
  };

  this._type_of_symbol = function(me, symbol) {
    if (this._symbol_is_operator(me, symbol)) {
      return 'operator';
    }
    if (this._symbol_is_component(me, symbol)) {
      return 'component';
    }
    return 'other';
  };

  this.parse = function(source) {
    return this._parse(this.parse_tree(source));
  };

  this._parse = function(element) {
    var token;
    if (this._isa_token(null, element)) {
      return element.s;
    }
    return (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = element.length; i < len; i++) {
        token = element[i];
        results.push(this._parse(token));
      }
      return results;
    }).call(this);
  };

  this._err = function(me, idx, message) {
    var tokens_txt;
    tokens_txt = this._rpr_tokens(me, idx);
    throw new Error(message + " " + tokens_txt);
  };

  this.parse_tree = function(source) {
    var R, me, ref, type;
    if ((type = CND.type_of(source)) !== 'text') {
      throw new Error("expected a text, got a " + type);
    }
    if (!(source.length > 0)) {
      throw new Error("IDL: empty text");
    }
    me = this._new_parse(source);
    R = this._parse_tree(me);
    if (me.idx !== me.tokens.length) {
      this._err(me, me.idx, "IDL: extra token(s)");
    }
    if ((me.tokens.length === 1) && ((ref = (type = me.tokens[0].t)) === 'other' || ref === 'component')) {
      this._err(me, 0, "IDL: lone token of type " + (rpr(type)));
    }
    return R;
  };

  this._parse_tree = function(me, R) {
    var arity, count, i, ref, target, token, type;
    if (R == null) {
      R = null;
    }
    token = me.tokens[me.idx];
    if (token == null) {
      this._err(me, me.idx - 1, "IDL: premature end of source");
    }
    me.idx += +1;
    target = null;
    arity = null;
    switch (type = token.t) {
      case 'operator':
        arity = token.a;
        target = [token];
        for (count = i = 1, ref = arity; i <= ref; count = i += +1) {
          this._parse_tree(me, target);
        }
        if (R != null) {
          R.push(target);
        } else {
          R = target;
        }
        break;
      case 'component':
        if (R != null) {
          R.push(token);
        } else {
          R = token;
        }
        break;
      default:
        this._err(me, me.idx - 1, "IDL: illegal token " + (rpr(token.s)) + " (type " + (rpr(type)) + ")");
    }
    return R;
  };

  this._parsetree_as_text = function(me, parse_tree) {
    var R, element, i, len;
    R = [];
    for (i = 0, len = parse_tree.length; i < len; i++) {
      element = parse_tree[i];
      if (this._isa_token(me, element)) {
        R.push(element.s);
      } else {
        R.push(this._parsetree_as_text(me, element));
      }
    }
    return R.join('');
  };

}).call(this);

//# sourceMappingURL=idl.js.map
