// Generated by CoffeeScript 1.10.0
(function() {
  var CND, MKNCR, O, alert, badge, debug, echo, help, info, log, rpr, urge, warn, whisper,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MOJIKURA-IDL/IDL';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  MKNCR = require('mingkwai-ncr');

  O = require('./options');

  this.grammar = O.idl;

  this._new_parse = function(source) {
    var R;
    R = {
      '~isa': 'MOJIKURA-IDL/IDL/parse',
      source: source,
      stack: [],
      idx: 0
    };
    R.tokens = this._tokenize(R, source);
    return R;
  };

  this._tokenize = function(me, source) {
    var R, chrs, cu_idx, i, len, symbol;
    R = [];
    chrs = MKNCR.chrs_from_text(source);
    cu_idx = 0;
    for (i = 0, len = chrs.length; i < len; i++) {
      symbol = chrs[i];
      R.push(this._new_token(me, symbol, cu_idx));

      /* we're counting JS code units here */
      cu_idx += symbol.length;
    }
    return R;
  };

  this._new_token = function(me, symbol, cu_idx) {
    var R, operator, type;
    type = this._type_of_symbol(me, symbol);

    /* `t` for 'type' */
    R = {
      s: symbol,
      idx: cu_idx,
      t: type
    };
    switch (type) {
      case 'operator':
        operator = this._operator_from_symbol(me, symbol);
        R.a = operator.arity;
        R.n = operator.name;
    }
    return R;
  };

  this._operator_from_symbol = function(me, symbol) {
    var R;
    if ((R = this.grammar.operators[symbol]) == null) {
      throw new Error("symbol not known to be an operator: " + (rpr(symbol)));
    }
    return R;
  };

  this._symbol_is_operator = function(me, symbol) {
    return symbol in this.grammar.operators;
  };

  this._symbol_is_component = function(me, symbol) {
    var ref;
    return indexOf.call((ref = (MKNCR.describe(symbol)).tag) != null ? ref : [], 'cjk') >= 0;
  };

  this._type_of_symbol = function(me, symbol) {
    if (this._symbol_is_operator(me, symbol)) {
      return 'operator';
    }
    if (this._symbol_is_component(me, symbol)) {
      return 'component';
    }
    return 'other';
  };

  this.parse = function(source) {
    return this._parse(this.as_csl(source));
  };

  this._parse = function(csl) {
    var R, i, len, token;
    if (!CND.isa_list(csl)) {
      return csl.s;
    }
    R = [];
    for (i = 0, len = csl.length; i < len; i++) {
      token = csl[i];
      R.push(this._parse(token));
    }
    return R;
  };

  this.as_csl = function(source) {
    var R, me, type;
    if ((type = CND.type_of(source)) !== 'text') {
      throw new Error("expected a text, got a " + type);
    }
    if (!(source.length > 0)) {
      throw new Error("syntax error (empty text)");
    }
    me = this._new_parse(source);
    R = this._as_csl(me);
    if (me.idx !== me.tokens.length) {
      throw new Error("syntax error (token idx " + me.idx + " of " + (rpr(me.source)) + ")");
    }
    return R;
  };

  this._as_csl = function(me, R) {
    var arity, count, i, ref, target, token, type;
    if (R == null) {
      R = null;
    }
    token = me.tokens[me.idx];
    if (token == null) {
      throw new Error("syntax error (premature end of source " + (rpr(me.source)) + ")");
    }
    me.idx += +1;
    target = null;
    arity = null;
    switch (type = token.t) {
      case 'operator':
        arity = token.a;
        target = [token];
        for (count = i = 1, ref = arity; i <= ref; count = i += +1) {
          this._as_csl(me, target);
        }
        if (R != null) {
          R.push(target);
        } else {
          R = target;
        }
        break;
      case 'component':
        if (R != null) {
          R.push(token);
        } else {
          R = token;
        }
        break;
      default:
        throw new Error("unable to parse token of type " + type + " (token idx " + me.idx + " of " + (rpr(me.source)) + ")");
    }
    return R;
  };

}).call(this);

//# sourceMappingURL=idl.js.map
