// Generated by CoffeeScript 1.10.0
(function() {
  var CND, IDL, IDLX, MKNCR, O, alert, badge, debug, echo, help, info, log, rpr, urge, warn, whisper;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MOJIKURA-IDL';

  badge = 'MOJIKURA-IDL/IDLX';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  MKNCR = require('mingkwai-ncr');

  O = require('./options');

  IDL = require('./idl');

  this._parser_settings = O.idlx;

  this._lexeme_is_solitaire = function(me, lexeme) {
    return lexeme in me.settings.solitaires;
  };

  this._lexeme_is_proxy = function(me, lexeme) {
    return lexeme in me.settings.proxies;
  };

  this._lexeme_is_lbracket = function(me, lexeme) {
    var ref;
    return ((ref = me.settings.brackets[lexeme]) != null ? ref.name : void 0) === 'lbracket';
  };

  this._lexeme_is_rbracket = function(me, lexeme) {
    var ref;
    return ((ref = me.settings.brackets[lexeme]) != null ? ref.name : void 0) === 'rbracket';
  };

  this._type_of_lexeme = function(me, lexeme) {
    var R;
    R = IDL._type_of_lexeme.call(IDLX, me, lexeme);
    if (this._lexeme_is_solitaire(me, lexeme)) {
      return 'solitaire';
    }
    if (this._lexeme_is_proxy(me, lexeme)) {
      return 'proxy';
    }
    if (this._lexeme_is_lbracket(me, lexeme)) {
      return 'lbracket';
    }
    if (this._lexeme_is_rbracket(me, lexeme)) {
      return 'rbracket';
    }
    return R;
  };

  this._token_is_rbracket = function(me, x) {
    return (this._isa_token(me, x)) && x.t === 'rbracket';
  };

  this._token_is_constituent = function(me, x) {
    var ref;
    return (this._isa_token(me, x)) && ((ref = x.t) === 'component' || ref === 'proxy');
  };

  this._get_next_token = function(me, mode) {
    var R;
    R = me.tokens[me.idx];
    if (R == null) {
      this._err(me, me.idx - 1, "IDLX: premature end of source");
    }
    if (mode !== 'peek') {
      this._advance(me);
    }
    return R;
  };

  this._peek_next_token = function(me) {
    return this._get_next_token(me, 'peek');
  };

  this._advance = function(me) {
    return me.idx += +1;
  };

  this._try_to_advance = function(me) {
    if (me.idx < me.tokens.length - 1) {
      return me.idx += +1;
    }
  };

  this._parse_tree = function(me, R) {
    var advance, arity, count, i, next_token, ref, target, token, type;
    if (R == null) {
      R = null;
    }
    advance = false;
    while (true) {
      token = this._get_next_token(me);
      target = null;
      arity = null;
      switch (type = token.t) {
        case 'lbracket':
          advance = true;
          continue;
        case 'rbracket':
          this._err(me, me.idx - 1, "IDLX: unexpected right bracket");
          break;
        case 'operator':
          if (advance) {
            if (!(token.a > 1)) {
              this._err(me, me.idx - 1, "IDLX: cannot bracket unary operator");
            }
            target = [token];
            while (true) {
              next_token = this._peek_next_token(me);
              if (this._token_is_rbracket(me, next_token)) {
                if (!(target.length - 1 > token.a)) {
                  this._err(me, me.idx, "IDLX: too few constituents");
                }
                this._advance(me);
                break;
              } else if (this._token_is_constituent(me, next_token)) {
                target.push(next_token);
                this._advance(me);
              } else {
                target.push(this._parse_tree(me));
              }
            }
          } else {
            arity = token.a;
            target = [token];
            for (count = i = 1, ref = arity; i <= ref; count = i += +1) {
              this._parse_tree(me, target);
            }
          }
          if (R != null) {
            R.push(target);
          } else {
            R = target;
          }
          break;
        case 'component':
        case 'solitaire':
        case 'proxy':
          if ((type === 'solitaire') && ((me.idx !== 1) || (me.tokens.length > 1))) {
            this._err(me, me.idx - 1, "IDLX: cannot have a solitaire here");
          }
          if (R != null) {
            R.push(token);
          } else {
            R = token;
          }
          break;
        default:
          this._err(me, me.idx - 1, "IDLX: illegal token " + (rpr(token.s)) + " (type " + (rpr(type)) + ")");
      }
      break;
    }
    return R;
  };


  /* Poor Man's MultiMix: */

  module.exports = IDLX = Object.assign(CND.deep_copy(IDL), this);

}).call(this);

//# sourceMappingURL=idlx.js.map
