// Generated by CoffeeScript 1.10.0
(function() {
  var CND, IDL, IDLX, MKNCR, O, alert, badge, debug, echo, help, info, log, rpr, urge, warn, whisper;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MOJIKURA-IDL';

  badge = 'MOJIKURA-IDL/IDLX';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  MKNCR = require('mingkwai-ncr');

  O = require('./options');

  IDL = require('./idl');

  this.grammar = O.idlx;

  this._symbol_is_solitaire = function(me, symbol) {
    return symbol in this.grammar.solitaires;
  };

  this._symbol_is_proxy = function(me, symbol) {
    return symbol in this.grammar.proxies;
  };

  this._type_of_symbol = function(me, symbol) {
    var R;
    R = IDL._type_of_symbol.call(IDLX, me, symbol);
    if (this._symbol_is_solitaire(me, symbol)) {
      return 'solitaire';
    }
    if (this._symbol_is_proxy(me, symbol)) {
      return 'proxy';
    }
    return R;
  };

  this._parse_tree = function(me, R) {
    var arity, count, i, ref, target, token, type;
    if (R == null) {
      R = null;
    }
    token = me.tokens[me.idx];
    if (token == null) {
      this._mark_token(me, me.idx - 1);
      throw new Error("syntax error: premature end of source in " + (rpr(me.tokens)) + ")");
    }
    me.idx += +1;
    target = null;
    arity = null;
    switch (type = token.t) {
      case 'operator':
        arity = token.a;
        target = [token];
        for (count = i = 1, ref = arity; i <= ref; count = i += +1) {
          this._parse_tree(me, target);
        }
        if (R != null) {
          R.push(target);
        } else {
          R = target;
        }
        break;
      case 'component':
      case 'solitaire':
      case 'proxy':
        if (R != null) {
          R.push(token);
        } else {
          R = token;
        }
        break;
      default:
        this._mark_token(me);
        throw new Error("syntax error: illegal token (type " + (rpr(type)) + ") in " + (rpr(me.tokens)));
    }
    return R;
  };


  /* Poor Man's MultiMix: */

  module.exports = IDLX = Object.assign(CND.deep_copy(IDL), this);

}).call(this);

//# sourceMappingURL=idlx.js.map
