// Generated by CoffeeScript 1.10.0
(function() {
  var CND, MKNCR, O, alert, badge, debug, echo, help, info, log, rpr, urge, warn, whisper,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MOJIKURA/IDL';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  MKNCR = require('mingkwai-ncr');

  O = require('./options');

  this._new_parse = function(source) {
    var R;
    R = {
      '~isa': 'MOJIKURA/IDL/parse',
      grammar: O.idl,
      source: source,
      stack: [],
      idx: 0
    };
    R.tokens = this._tokenize(R, source);
    return R;
  };

  this._tokenize = function(me, source) {
    var R, chrs, cu_idx, i, len, symbol;
    R = [];
    chrs = MKNCR.chrs_from_text(source);
    cu_idx = 0;
    for (i = 0, len = chrs.length; i < len; i++) {
      symbol = chrs[i];
      R.push(this._new_token(me, symbol, cu_idx));

      /* we're counting JS code units here */
      cu_idx += symbol.length;
    }
    return R;
  };

  this._new_token = function(me, symbol, cu_idx) {
    var R, operator, type;
    type = this._type_of_symbol(me, symbol);

    /* `t` for 'type' */
    R = {
      s: symbol,
      idx: cu_idx,
      t: type
    };
    switch (type) {
      case 'operator':
        operator = this._operator_from_symbol(me, symbol);
        R.a = operator.arity;
        R.n = operator.name;
    }
    return R;
  };

  this._operator_from_symbol = function(me, symbol) {
    var R;
    if ((R = me.grammar.operators[symbol]) == null) {
      throw new Error("symbol not known to be an operator: " + (rpr(symbol)));
    }
    return R;
  };

  this._symbol_is_operator = function(me, symbol) {
    return symbol in me.grammar.operators;
  };

  this._symbol_is_component = function(me, symbol) {
    var ref;
    return indexOf.call((ref = (MKNCR.describe(symbol)).tag) != null ? ref : [], 'cjk') >= 0;
  };

  this._type_of_symbol = function(me, symbol) {
    if (this._symbol_is_operator(me, symbol)) {
      return 'operator';
    }
    if (this._symbol_is_component(me, symbol)) {
      return 'component';
    }
    return 'other';
  };

  this.parse = function(source) {
    var R, me;
    me = this._new_parse(source);
    R = this._parse(me);
    return R;
  };

  this._parse = function(me, R) {
    var arity, count, i, operator_count, ref, target, token, type;
    if (R == null) {
      R = null;
    }
    if (R == null) {
      R = [];
    }
    token = me.tokens[me.idx];
    me.idx += +1;
    operator_count = 0;
    target = null;
    arity = null;
    debug('30211', token);
    switch (type = token.t) {
      case 'operator':
        operator_count += +1;
        arity = token.a;
        target = [token];
        R.push(target);
        for (count = i = 1, ref = arity; i <= ref; count = i += +1) {
          this._parse(me, target);
        }
        break;
      case 'component':
        R.push(token);
        break;
      default:
        throw new Error("unable to parse token of type " + type + "\n" + me.source + "\n" + idx);
    }
    return R;
  };

  this.demo = function() {
    var i, len, p, results, source, sources;
    sources = ['⿲木木木', '⿱癶⿰弓貝', '⿱⿰亻式貝', '⿱⿰亻式⿱目八'];
    results = [];
    for (i = 0, len = sources.length; i < len; i++) {
      source = sources[i];
      help(source);
      p = this.parse(source);
      results.push(urge('\n' + rpr(p)));
    }
    return results;
  };

  if (module.parent == null) {
    this.demo();
  }

}).call(this);

//# sourceMappingURL=main.js.map
