// Generated by CoffeeScript 2.3.1
(function() {
  //###########################################################################################################
  var CND, badge, debug, help, info, rpr, urge, warn, whisper;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'KBM/MIXINS/IPC';

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  // { IDLX, }            = require '../../../mojikura-idl'

  //-----------------------------------------------------------------------------------------------------------
  /* TAINT patterns should be derived from options or grammar */
  this._silhouette_binary_operator_pattern = /[⿰⿱⿴⿵⿶⿷⿸⿹⿺⿻◰]/g;

  this._silhouette_unary_operator_pattern = /[≈<>?↻↔↕]/g;

  this._silhouette_singleton_pattern = /[∅●▽]/g;

  /* TAINT will fail silently if we ever introduce singleton symbols from beyond U+ffff */
  this._silhouette_element_pattern = /(?:&[a-z0-9]*\#(?:x[a-f0-9]+|[0-9]+);)|(?:[\ud800-\udbff][\udc00-\udfff])|[^()bus]/g;

  //-----------------------------------------------------------------------------------------------------------
  this.silhouette_from_formula = function(formula) {
    var R;
    R = formula;
    R = R.replace(this._silhouette_binary_operator_pattern, 'b');
    R = R.replace(this._silhouette_unary_operator_pattern, 'u');
    R = R.replace(this._silhouette_singleton_pattern, 's');
    R = R.replace(this._silhouette_element_pattern, '.');
    return R;
  };

}).call(this);

//# sourceMappingURL=silhouettes.js.map
